[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "hyperelastic_solver"
version = "0.1.0"
description = "Nonlinear quasi-static hyperelastic solver with DOLFINx, together with tools for ROM."
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name = "Theron Guo" }]

[tool.setuptools]
packages = ["hyperelastic_solver", "rve_rom"]
