"""Linear buckling modes of the periodic hexagonal RVE (micromorphic solver).

Stage 1 of the micromorphic workflow on the porous *hexagonal* RVE
(``hexagonal_rve.msh``, generated by ``generate_hexagonal_mesh.py``). Unlike the
square RVEs in ``examples/mm/example_1``, this cell is an arbitrary 2D periodic
polygon, so periodicity is enforced through the new geometric *lattice-vector*
path of :class:`fe2_rom.ch1.MicroSolver` (``lattice_vectors=...``) rather than
the axis-aligned box logic. Opposite hexagon edges (and the solid-junction
vertices) are auto-paired from the two lattice vectors; the half-hole arcs at the
edge midpoints and the central hole are correctly left as traction-free void
surfaces.

This script only computes and visualises the linear buckling modes ``φᵢ`` and
their eigenvalues, then stops — no macro (v, g) solve.

Run:
    conda activate fe2_rom_env
    python run_micromorphic.py
"""
import os
# Keep nested linear-algebra single-threaded to avoid oversubscription.
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"

import logging
import numpy as np
from mpi4py import MPI

from fe2_rom.hyperelastic_solver import NeoHookean, setup_logging
from fe2_rom.mm.microsolver import MicroSolver


# --- Logging ----------------------------------------------------------------
comm = MPI.COMM_WORLD
setup_logging(comm, level=logging.INFO)
logger = logging.getLogger("fe2_rom.mm.example_4")
logger.addFilter(lambda r: comm.rank == 0)


# --- Mesh + periodicity -----------------------------------------------------
HERE = os.path.dirname(__file__)
RVE_MESH = os.path.abspath(os.path.join(HERE, "hexagonal_rve.msh"))


def hexagon_lattice_from_mesh(path):
    """Infer the pointy-top hexagon geometry from the mesh bounding box and
    return ``(lattice_vectors, cell_area)``.

    The mesh spans ``x ∈ [-ℓ, ℓ]`` (vertical left/right edges, apothem ℓ) and
    ``y ∈ [-R, R]`` (top/bottom vertices, circumradius R = 2ℓ/√3). The three
    opposite-edge translations are the near-neighbour lattice vectors; a
    primitive basis is ``a1 = (2ℓ, 0)`` (left↔right) and ``a2 = (ℓ, √3 ℓ)`` (one
    slanted pair). Regular-hexagon area ``|Q| = 2√3 ℓ²``.
    """
    ell = R = None
    if comm.rank == 0:
        import gmsh
        gmsh.initialize()
        gmsh.option.setNumber("General.Terminal", 0)
        try:
            gmsh.open(path)
            xy = gmsh.model.mesh.getNodes()[1].reshape(-1, 3)[:, :2]
        finally:
            gmsh.finalize()
        ell = 0.5 * (xy[:, 0].max() - xy[:, 0].min())
        R = 0.5 * (xy[:, 1].max() - xy[:, 1].min())
    ell, R = comm.bcast((ell, R), root=0)
    s3 = np.sqrt(3.0)
    lattice = np.array([[2.0 * ell, 0.0],
                        [ell, s3 * ell]])
    area = 2.0 * s3 * ell ** 2
    logger.info("Hexagon: apothem ℓ=%.6f, circumradius R=%.6f, |Q|=%.6f", ell, R, area)
    return lattice, area


LATTICE_VECTORS, RVE_VOLUME = hexagon_lattice_from_mesh(RVE_MESH)


# --- Material ---------------------------------------------------------------
E_micro, nu_micro = 3000.0, 0.30
mu_micro = E_micro / (2.0 * (1.0 + nu_micro))
lam_micro = E_micro * nu_micro / ((1.0 + nu_micro) * (1.0 - 2.0 * nu_micro))

output_dir = os.path.join(HERE, "output")
os.makedirs(output_dir, exist_ok=True)


# --- Stage 1: linear buckling spectrum (cheap, N=0) ------------------------
# Built with N=0: a plain full-periodicity homogenization solver (no micromorphic
# φ machinery), so the linear buckling spectrum is cheap. We always compute N_EIG
# modes and then auto-select how many to keep from the "sudden decay" (the largest
# spectral gap) — see auto_select_n_modes below.
N_EIG = 8            # number of buckling modes / eigenvalues to compute
spec_solver = MicroSolver(
    mesh_path=RVE_MESH,
    comm=comm,
    gdim=2,
    material=NeoHookean(mu=mu_micro, lmbda=lam_micro),
    N=0,
    degree=2,
    output_dir=output_dir,
    check_stability=False,            # only the linear buckling eigensolve is needed
    visualize_fields=[],
    newton_options={"rel_tol": 1e-8, "abs_tol": 1e-6,
                    "max_iter": 50, "div_rel_tol": 10,
                    "switch_to_minres": True},
    timestepper_options={"t_end": 1.0, "dt_init": 1e-2, "dt_min": 1e-5,
                         "dt_max": 1e-2, "good_newton_steps": 5},
    rve_volume=RVE_VOLUME,
    lattice_vectors=LATTICE_VECTORS,
)
logger.info("Periodic MPC: %d slave dofs (polygon/lattice path)",
            comm.allreduce(len(spec_solver.mpc.slaves), op=MPI.SUM))

# Reference state defaults to the undeformed cell (F̄ = I): the softest
# deformation modes. To capture true buckling under compression, pass e.g.
# Fbar=np.array([[0.9, 0.0], [0.0, 1.0]]) (close to / past the critical load).
# n_skip defaults to gdim+1 (rigid translations + 1 MPC gauge mode); the skipped
# eigenvalues are logged so the count can be checked.
eigvals = spec_solver.compute_buckling_spectrum(
    N_EIG, Fbar=None,
    visualize_modes=True,                 # -> output/buckling_spectrum.bp
    modes_filename="buckling_spectrum.bp",
    save_eigvals=True,                    # -> output/snapshots/buckling_eigvals.npy
)


def auto_select_n_modes(eigvals, min_gap_ratio=3.0):
    """Choose N_MODES at the 'sudden decay' in the ascending buckling spectrum.

    The eigenvalues come sorted smallest-first; the largest relative jump
    ``λ_{i+1}/λ_i`` separates the soft (buckling-relevant) cluster from the
    stiff rest. Returns the number of modes before that gap. If no jump exceeds
    ``min_gap_ratio`` (no clear separation), keep all computed modes.
    """
    e = np.abs(np.asarray(eigvals, dtype=float))
    e = e[np.isfinite(e)]
    if e.size <= 1:
        return int(e.size)
    ratios = e[1:] / np.maximum(e[:-1], 1e-30)
    k = int(np.argmax(ratios))
    return (k + 1) if ratios[k] >= min_gap_ratio else int(e.size)


N_MODES = auto_select_n_modes(eigvals)

gaps = np.abs(eigvals[1:]) / np.maximum(np.abs(eigvals[:-1]), 1e-30)
logger.info("Linear buckling eigenvalues (physical, smallest |λ|):")
for i, lam in enumerate(eigvals):
    logger.info("  mode %d :  λ = %.6e", i, lam)
logger.info("Spectral gaps λ_{i+1}/λ_i: %s", np.array2string(gaps, precision=2))
logger.info("→ Auto-selected N_MODES = %d (soft cluster before the largest spectral gap); "
            "spectrum modes in %s/buckling_spectrum.bp", N_MODES, output_dir)


# --- Stage 2: build the micromorphic solver and populate the φ basis --------
# Rebuild with N=N_MODES (the auto-selected count) and load the softest buckling
# modes into self._phi via compute_linear_buckling_modes (the micromorphic
# populate API — distinct from the spectrum inspection above).
logger.info("Rebuilding micromorphic solver with N=%d mode(s) …", N_MODES)
solver = MicroSolver(
    mesh_path=RVE_MESH,
    comm=comm,
    gdim=2,
    material=NeoHookean(mu=mu_micro, lmbda=lam_micro),
    N=N_MODES,
    degree=2,
    output_dir=output_dir,
    check_stability=False,
    visualize_fields=["u_fluc", "u_total", "F", "P"],
    newton_options={"rel_tol": 1e-8, "abs_tol": 1e-6,
                    "max_iter": 50, "div_rel_tol": 10,
                    "switch_to_minres": True},
    timestepper_options={"t_end": 1.0, "dt_init": 1e-1, "dt_min": 1e-5,
                         "dt_max": 1e-1, "good_newton_steps": 5},
    rve_volume=RVE_VOLUME,
    lattice_vectors=LATTICE_VECTORS,
)
phi_eigvals = solver.compute_linear_buckling_modes(
    N_MODES, Fbar=None,
    visualize_modes=True,     # -> output/buckling_modes.bp
    save_modes=True,          # -> output/snapshots/phi_*.npy + buckling_eigvals.npy
)
logger.info("φ basis populated with %d mode(s): λ = %s",
            N_MODES, np.array2string(phi_eigvals, precision=4))


# --- Stage 3: micromorphic probe — prescribe (F̄, v, g), report the response -
Fbar_target = np.array([[0.95, 0.0],
                        [0.00, 1.0]])
v_target = np.zeros(N_MODES)
v_target[0] = 0.5
g_target = np.zeros((N_MODES, 2))
g_target[0] = (-0.1, 0.05)

logger.info("Micromorphic solve at F̄_xx=%.3f, v[0]=%.2f, g[0]=%s …",
            Fbar_target[0, 0], v_target[0], np.round(g_target[0], 3))
results = solver(Fbar_target, v_target, g_target)
final = results[-1]

# Constraint violation check (⟨w⟩, ⟨w·φᵢ⟩, ⟨(w·φᵢ)X⟩ should all be ~0).
w_vec = solver.u.x.petsc_vec
c_vecs = solver._newton._constraint_vecs
if c_vecs:
    viols = [abs(c.dot(w_vec)) for c in c_vecs]
    logger.info("Constraint violations (should be ~0): max=%.3e", max(viols))

if comm.rank == 0:
    logger.info("── Effective quantities (final load) ──")
    for key in ("Fbar", "Pbar", "Pi", "Lambda"):
        logger.info("  %-8s shape=%s\n%s", key, np.shape(final[key]), np.asarray(final[key]))
    logger.info("── Tangent block norms ──")
    for key in sorted(k for k in final if k.startswith("d")):
        arr = np.asarray(final[key])
        logger.info("  %-15s shape=%s  |.|=%.4e", key, arr.shape, np.linalg.norm(arr))
    np.savez(os.path.join(output_dir, "micromorphic_results.npz"),
             **{k: np.asarray(v) for k, v in final.items()})
    logger.info("Saved results to %s/micromorphic_results.npz", output_dir)


# --- History plots (mode 0) -------------------------------------------------
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

Fbar_hist = np.array([np.asarray(r["Fbar"]) for r in results])
Pbar_hist = np.array([np.asarray(r["Pbar"]) for r in results])
Pi_hist = np.array([np.asarray(r["Pi"]) for r in results])
Lam_hist = np.array([np.asarray(r["Lambda"]) for r in results])
A_hist = np.array([np.asarray(r["dPbar_dFbar"]) for r in results])
dPidv_h = np.array([np.asarray(r["dPi_dv"]) for r in results])
dLamdg_h = np.array([np.asarray(r["dLambda_dg"]) for r in results])

F00 = Fbar_hist[:, 0, 0]
denom = (1.0 - Fbar_target[0, 0]) or 1.0
t_ramp = (1.0 - F00) / denom
v0_hist = t_ramp * v_target[0]
gx_hist = t_ramp * g_target[0, 0]

if comm.rank == 0:
    fig, axes = plt.subplots(2, 3, figsize=(13, 7))
    axes[0, 0].plot(F00, Pbar_hist[:, 0, 0], "-o", ms=3)
    axes[0, 0].set(xlabel=r"$\bar F_{xx}$", ylabel=r"$\bar P_{xx}$")
    axes[0, 1].plot(v0_hist, Pi_hist[:, 0], "-o", ms=3)
    axes[0, 1].set(xlabel=r"$v_0$", ylabel=r"$\Pi_0$")
    axes[0, 2].plot(gx_hist, Lam_hist[:, 0, 0], "-o", ms=3)
    axes[0, 2].set(xlabel=r"$g_{0,x}$", ylabel=r"$\Lambda_{0,x}$")
    axes[1, 0].plot(F00, A_hist[:, 0, 0, 0, 0], "-o", ms=3)
    axes[1, 0].set(xlabel=r"$\bar F_{xx}$", ylabel=r"$\bar A_{xxxx}$")
    axes[1, 1].plot(F00, dPidv_h[:, 0, 0], "-o", ms=3)
    axes[1, 1].set(xlabel=r"$\bar F_{xx}$", ylabel=r"$d\Pi_0/dv_0$")
    axes[1, 2].plot(F00, dLamdg_h[:, 0, 0, 0, 0], "-o", ms=3)
    axes[1, 2].set(xlabel=r"$\bar F_{xx}$", ylabel=r"$d\Lambda_{0,x}/dg_{0,x}$")
    for ax in axes.ravel():
        ax.grid(True, alpha=0.3)
    fig.tight_layout()
    plot_path = os.path.join(output_dir, "micromorphic_history.png")
    fig.savefig(plot_path, dpi=150)
    plt.close(fig)
    logger.info("Saved history plots to %s", plot_path)
